build:
  image: golang:1.5
  environment:
    - CGO_ENABLED=0
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  coverage:
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-hipchat
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-hipchat
    tag: develop
    when:
      branch: develop

plugin:
  name: HipChat
  desc: Send build status notifications via HipChat
  type: notify
  image: plugins/drone-hipchat
  labels:
    - chat
    - messaging
    - hipchat
