workspace:
  base: /go
  path: src/github.com/drone-plugins/drone-hipchat

pipeline:
  build:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
    commands:
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.revision=$(git rev-parse HEAD)" -a

  # coverage:
  #   when:
  #     branch: master
  #
  # docker:
  #   username: $$DOCKER_USER
  #   password: $$DOCKER_PASS
  #   email: $$DOCKER_EMAIL
  #   repo: plugins/drone-hipchat
  #   tag: latest
  #   when:
  #     branch: master
  # docker:
  #   username: $$DOCKER_USER
  #   password: $$DOCKER_PASS
  #   email: $$DOCKER_EMAIL
  #   repo: plugins/drone-hipchat
  #   tag: develop
  #   when:
  #     branch: develop

plugin:
  name: HipChat
  desc: Send build status notifications via HipChat
  type: notify
  image: plugins/drone-hipchat
  labels:
    - chat
    - messaging
    - hipchat
